experiment_name: gsm8k-ppo-lora-multiagent-joint
trial_name: trial0

# Multi-agent 特定配置
n_agents: 2
agent_interaction_mode: sequential  # 或 parallel, communication

seed: 1
total_train_epochs: 10
tokenizer_path: ${actor.path}
async_training: false  # 改为同步，确保联合推理完成后再训练

cluster:
  n_nodes: 1
  n_gpus_per_node: 8
  fileroot: /inspire/hdd/project/multi-agent/liaojunwei-p-liaojunwei/codes/areal-marft/AReaL-MARFT/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /inspire/hdd/project/multi-agent/liaojunwei-p-liaojunwei/codes/areal-marft/AReaL-MARFT/name_resolve

# 所有 agents 共享同一套资源分配
allocation_mode: sglang:d1p1t1+d1p1t1

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 128  # 减半以容纳多 agent
  queue_size: null
  consumer_batch_size: 128
  max_head_offpolicyness: 4
  enable_rollout_tracing: true  # 开启 tracing 用于调试
  pause_grace_period: 1.0

gconfig:
  n_samples: 1
  min_new_tokens: 0
  max_new_tokens: 512
  greedy: false
  temperature: 1.0

# Actor/Critic 配置作为模板，每个 agent 会复制
actor:
  experiment_name: ${experiment_name}  # 运行时会添加 _agent{id}
  trial_name: ${trial_name}
  path: /inspire/hdd/project/multi-agent/liaojunwei-p-liaojunwei/models/Qwen2.5-1.5B-Instruct
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: false
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 8192  # 降低以节省显存
  optimizer:
    type: adam
    lr: 3e-5
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  group_size: ${gconfig.n_samples}
  eps_clip: 0.4
  temperature: ${gconfig.temperature}
  reward_scaling: 10.0
  reward_bias: -0.5
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0
  dynamic_sampling: false
  max_new_tokens: ${gconfig.max_new_tokens}
  use_lora: true
  peft_type: lora
  lora_rank: 32
  lora_alpha: 16
  target_modules: [all-linear]

critic:
  is_critic: true
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  eps_clip: 0.5
  ppo_n_minibatches: ${actor.ppo_n_minibatches}
  mb_spec:
    max_tokens_per_mb: 8192
  optimizer: ${actor.optimizer}

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 1024
  optimizer: null

sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  max_running_requests: 64  # 控制并发
  context_length: 32768
  mem_fraction_static: 0.75  # 降低以容纳多 agent
  enable_lora: ${actor.use_lora}
  max_lora_rank: ${actor.lora_rank}
  lora_target_modules: ${actor.target_modules}
  schedule_policy: fcfs

train_dataset:
  batch_size: 128  # 减半
  shuffle: true
  drop_last: true
  pin_memory: true
  num_workers: 4
  path: /inspire/hdd/project/multi-agent/liaojunwei-p-liaojunwei/data/gsm8k
  type: rl
  max_length: 1024

valid_dataset:
  batch_size: 128
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: /inspire/hdd/project/multi-agent/liaojunwei-p-liaojunwei/data/gsm8k
  type: rl

saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: disabled
  tensorboard:
    path: ${cluster.fileroot}/${experiment_name}/${trial_name}

launcher:
  inference_server_cpus_per_gpu: 15
  inference_server_mem_per_gpu: 32768
  trainer_cpus_per_gpu: 15
  trainer_mem_per_gpu: 32768